---
name: "vale"

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staticrocket/processor-sdk-doc:latest
      options: --entrypoint /bin/bash

    steps:
      - name: Prepare GitHub workdir
        run: |
          mkdir -p /github/home/

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **.rst
            **.md

      - name: Run vale checks
        uses: errata-ai/vale-action@v2.1.1
        with:
          fail_on_error: true
          files: ${{ steps.changed-files.outputs.all_changed_files }}
